<div class="fieldset">
	<h3 class="legend"><?php echo $this->__('Please add a message:') ?></h3>
	<ul class="form-list">
		<li>
			<textarea id="react_message"></textarea>	
		</li>
	</ul>
	<div class="button-container" style="text-align: right;">
		<a href="javascript:reactBox.clearSession()"><?php echo $this->__('Cancel') ?></a>
		<button type="button" onclick="reactBox.postMessage()" class="button">
			<span><span><?php echo $this->__('Post Message') ?></span></span>
		</button>
	</div>
</div>