<?php $_helper = Mage::helper('react'); ?>
<div id="react_modalbox">	
	<div id="react_dialogbox" class="main">
	
	</div>
	<div id="react_overlay" style="display: none;"></div>
</div>
<script type="text/javascript">

	new Effect.Fade($('react_overlay'), {duration: 0});
	$('react_overlay').style.display = 'block';
	var reactBox = new React({
		varName: 'reactBox',
		translations: {
			continue: '<?php echo $this->__('Continue') ?>'
		},
		authenticateUrl: '<?php echo $this->getUrl('react/index/login') ?>',
		clearSessionUrl: '<?php echo $this->getUrl('react/index/clear') ?>',
		emailPostUrl: '<?php echo $this->getUrl('react/index/emailPost') ?>', 
		shareUrl: '<?php echo $this->getUrl('react/share/index') ?>',
		modeVar: '<?php echo $_helper::VAR_AJAX_MODE ?>',
		postMessageUrl: '<?php echo $this->getUrl('react/share/messagePost'); ?>'
	}); 
	<?php $email_data= $_helper->getSession()->getData($_helper::VAR_NOEMAIL) ?>
	<?php if($email_data): ?>
		reactBox.request('<?php echo $this->getUrl('react/index/emailForm'); ?>');
	<?php elseif($_helper->getSession()->getData($_helper::VAR_SHARE)): ?>
		reactBox.request('<?php echo $this->getUrl('react/share/message'); ?>')
	<?php endif; ?>
</script>