<div class="account-login react">
	<div class="page-title">
		<h1>Account Email</h1>
	</div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<form id="react-email" action="<?php echo $this->getUrl('react/index/emailPost') ?>" method="post">
		<div class="content">
			<p><?php echo $this->__('The email address provided by %s could not be verfied. Please register using this page.', $this->getProvider()) ?></p>
			<ul class="form-list">
				<li>
					<label class="required">
						<em>*</em>
						<?php echo $this->__('Email Address') ?>
					</label>
					<div class="input-box"><input class="input-text required-entry validate-email" type="text" name="email" title="Email Address" /></div>
				</li>
			</ul>
		</div>
		<div class="buttons-set">
			<button type="submit" class="button">
				<span><span><?php echo $this->__('Save') ?></span></span>
			</button>
		</div>
	</form>
</div>
<script type="text/javascript">
	var dataForm = new VarienForm('react-email', true);
</script>
