<?php $_defaults = $this->getDefaults() ?>
<?php $_helper = Mage::helper('react'); ?>
<div id="react_share"> 
	<button type="button" onclick="reactBox.share()" class="button">
		<span><span>Share</span></span>
	</button>
	
	<input type="hidden" name="react_url" value="<?php echo $_defaults['url'] ?>" />
	<input type="hidden" name="react_img" value="<?php echo $_defaults['img'] ?>" />
	<input type="hidden" name="react_title" value="<?php echo $_defaults['title'] ?>"/>
	<input type="hidden" name="react_description" value="<?php echo $_defaults['description'] ?>" />
</div>