<div class="page-title">
	<h1><?php echo $this->__('Social Accounts') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="fieldset">
	<h2 class="legend"><?php echo $this->__('Social Networks'); ?></h2>
	<table class="react-providers">
		<tbody>
			<?php foreach($this->getAccounts() as $provider => $active): ?>
			<tr>
				<td class="provider-container">
					<span class="image <?php echo strtolower($provider) ?>"></span><br /><br />
					<span><?php echo $provider ?></span>
				</td>
				<td>
					<?php $url = ($active) ? $this->getUrl('react/providers/remove',array('provider'=>$provider)) : $this->getUrl('react/providers/add',array('provider'=>$provider)); ?>
					<?php $label = ($active) ? $this->__('Remove') : $this->__('Connect'); ?>
					<?php if($active && $this->getDeadlock()): ?>
						<span class="action"><?php echo $this->__('You need at least one social account connected.') ?></span>
					<?php else: ?>
						<a class="action <?php if($active) echo 'connected'; ?>" href="<?php echo $url ?>"><?php echo $label ?></a>
					<?php endif; ?>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>